### ISSUE TITLE
User Story 003 - Inserir botão para editar valores

### ISSUE THREAD

**Issue by GeorgemCabral** [GeorgemCabral/PA2#3]
Identificador: E003
Complexidade: média
Prioridade: alta
Descrição: Como usuário, quero alterar os valores cadastrados no campo receitas e despesas. (Inserir botão de editar para que se possa alterar os valores digitados).

**Comment by ericknilsen** [comment]
Desnecessário. As estórias de manter receita e despesa já englobam esta.
